name: Deploy production-subsctiption to Plesk Server

on:
  push:
    branches: [production-subsctiption] 

jobs:
  sync:
    name: Build and sync WordPress files to server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up sshpass to use SSH password authentication
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Step 3: Deploy files to the remote server using rsync with password
      - name: Deploy development-wordpress files to server using rsync with password
        run: |
          # Use rsync with sshpass to pass the password and specify the SSH port
          sshpass -p "${{ secrets.PROD_PASSWORD }}" rsync -avzh --exclude=".git" --exclude="node_modules" -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.PROD_PORT }}" ./ ${{ secrets.PROD_USERNAME }}@${{ secrets.PROD_HOST }}:/var/www/vhosts/gibbs.no/httpdocs/subscription

        env:
          PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}  
          PROD_PORT: ${{ secrets.PROD_PORT }}  # Ensure this is set in GitHub secrets
